<?php
require __DIR__ . '/includes/bootstrap.php';
$currentPage = 'news'; $pageTitle = 'News | ' . $site['name'];
$records = load_data('news'); $featured = array_values(array_filter($records, static fn ($record) => !empty($record['featured'])));
$q = query_string('q'); $category = query_string('category'); $categories = array_values(array_unique(array_column($records, 'category')));
$filtered = array_values(array_filter($records, static function ($record) use ($q, $category) { $haystack = implode(' ', [$record['title'] ?? '', $record['summary'] ?? '', $record['category'] ?? '', $record['author'] ?? '']); return ($category === '' || $category === ($record['category'] ?? '')) && ($q === '' || stripos($haystack, $q) !== false); }));
require __DIR__ . '/includes/header.php';
?>
<main id="main" class="page-shell page-shell--news">
  <section class="page-hero page-hero--editorial"><div class="container page-hero-content"><p class="eyebrow">EDU2IMPACT / NEWS</p><h1>Ideas in motion.</h1><p>ข่าวสาร กิจกรรม และองค์ความรู้จากเครือข่าย Edu2Impact</p></div></section>
  <section class="container editorial-canvas">
    <div class="page-heading"><div><span class="section-kicker">FEATURED NEWS</span><h2>ข่าวสารโดดเด่น</h2></div><span class="item-count"><?= count($featured) ?> stories</span></div>
    <section class="news-featured-carousel" data-auto-carousel tabindex="0" aria-label="ข่าวสารโดดเด่น"><div class="carousel-viewport"><div class="carousel-track"><?php foreach ($featured as $record): ?><article class="carousel-card news-featured-card"><a class="carousel-card-media" href="<?= e(detail_url('news', $record['id'])) ?>"><img src="<?= e(image_path($record) ?: 'assets/images/content-placeholder.png') ?>" alt="" loading="lazy"></a><div class="carousel-card-body"><div class="post-meta"><span><?= e($record['category'] ?? 'News') ?></span><span><?= e($record['date'] ?? 'Coming soon') ?></span></div><h3><a href="<?= e(detail_url('news', $record['id'])) ?>"><?= e($record['title']) ?></a></h3><a class="read-link" href="<?= e(detail_url('news', $record['id'])) ?>">Read</a></div></article><?php endforeach; ?></div></div><button class="carousel-arrow carousel-arrow--prev" type="button" data-carousel-prev aria-label="ก่อนหน้า">‹</button><button class="carousel-arrow carousel-arrow--next" type="button" data-carousel-next aria-label="ถัดไป">›</button></section>
    <div class="page-heading page-heading--all"><div><span class="section-kicker">NEWS LIBRARY</span><h2>ข่าวสารทั้งหมด</h2></div><span class="item-count"><?= count($records) ?> updates</span></div>
    <form class="compact-search" method="get" action="news.php" role="search"><div class="search-field"><span aria-hidden="true">⌕</span><input id="news-search" type="search" name="q" value="<?= e($q) ?>" placeholder="Search news..." maxlength="200"><kbd>Ctrl K</kbd></div><label class="visually-hidden" for="news-category">หมวดหมู่</label><select id="news-category" name="category"><option value="">All categories</option><?php foreach ($categories as $option): ?><option value="<?= e($option) ?>"<?= $category === $option ? ' selected' : '' ?>><?= e($option) ?></option><?php endforeach; ?></select><button type="submit">Search</button></form>
    <div class="feed-heading"><span>News feed</span><span><?= count($filtered) ?> results</span></div><div class="editorial-feed" aria-live="polite"><?php foreach ($filtered as $record): ?><article class="editorial-post editorial-post--news"><a class="post-media" href="<?= e(detail_url('news', $record['id'])) ?>"><img src="<?= e(image_path($record) ?: 'assets/images/content-placeholder.png') ?>" alt="" loading="lazy"></a><div class="post-body"><div class="post-meta"><span><?= e($record['category'] ?? 'News') ?></span><span><?= e($record['date'] ?? 'Coming soon') ?></span></div><h3><a href="<?= e(detail_url('news', $record['id'])) ?>"><?= e($record['title']) ?></a></h3><p><?= e($record['summary']) ?></p><div class="post-footer"><span>By <?= e($record['author'] ?? 'Author to be added') ?></span><a href="<?= e(detail_url('news', $record['id'])) ?>">Read</a></div></div></article><?php endforeach; ?></div>
    <?php if (!$filtered): ?><div class="empty-state"><h2>No matching news</h2><p>ลองเปลี่ยนคำค้นหรือเลือกทุกหมวดหมู่</p></div><?php endif; ?>
  </section>
</main><?php require __DIR__ . '/includes/footer.php'; ?>
